import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Dock from "@/components/DockLayout";


export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};
// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
